# AutoSuspender config file (YAML format)
#
triggerProcessNames:  # process names (without ".exe") to check for ("trigger processes") (e.g. video games)
  - Overwatch
  - FortniteClient-Win64-Shipping
  - RocketLeague
  - gw2-64
  - java
  - CalculatorApp
targetProcessNames:   # process names (without ".exe") to suspend when trigger processes are running ("target processes")
  - chrome
  - brave
  - firefox
  - msedge
  - Spotify
  - WhatsApp
  - Signal
  - Minecraft
  - notepad
showNotifications: true          # do we display Windows action center notifications?
triggerProcessPollInterval: 120  # how often (in seconds) to poll trigger processes for memory stats (0 = no polling)